name: admin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  lib: ^0.0.3

  motif: ^0.0.6
  pocketbase: ^0.18.1
  get_it: ^7.6.7
  shared:
    path: ../shared
  provider: ^6.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


 

flutter:
  uses-material-design: true


  assets:
    - assets/
