name: admin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  lib: ^0.0.3

  motif: ^0.0.6
  pocketbase: ^0.18.1
  get_it: ^7.6.7
  shared:
    path: C:\Users\May-Tech\devup-bsc\shared
  provider: ^6.1.2
  shared_preferences: ^2.2.0
  date_format: ^2.0.9
  typed_data: ^1.4.0
  latlong2:
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


 

flutter:
  uses-material-design: true


  assets:
    - assets/
