name: app
description: Bumerdas Smart City App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: /Users/mohamad/Desktop/projects/devup/shared
  pocketbase: ^0.18.1
  go_router: ^13.1.0
  google_maps_flutter: ^2.5.3
  flutter_map: ^6.1.0 # For web support
  latlong2: ^0.9.0
  shimmer: ^3.0.0
  provider: ^6.1.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4
  flutter_map_cached_tile_provider: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true